### ISSUE TITLE
separate image facade core utilities 

### ISSUE THREAD

**Issue by jayunit100** [blackducksoftware/perceptor-scanner#66]
Lets gut as much code in the imagefacade package as we can into importable subpackages....  

- action.go
- model.go
- modelstate.go 
- The HTTPServer class (forgot what its called)
- ... others?

And put them into the common package (if we can).

Might make it easier to reverse engineer a custom image facade if we do that.

**Comment by mattfenwick** [comment]
These can already be imported and used from the current package ... the `common` package is called that because it's compiled into both the scanner and imagefacade containers.  The only things that should be in `common` are things that need to be compiled into both.  Most of the imagefacade stuff shouldn't be compiled into the scanner image.

**Comment by mattfenwick** [comment]
Looks like there's nothing actionable here.
